server:
  port: 8082

spring:
  application:
    name: user-service
    bad_request: 400
    conflict: 409
    success: 200
    not_found: 404

  security:
    enabled: true
    oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://host.docker.internal:8080/realms/banking-service
            audience: banking-service-client


  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:user_service}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


app:
  config:
    keycloak:
      server-url: http://host.docker.internal:8080
      realm: banking-service
      client-id: banking-service-client
      client-secret: SJD6MoROjlTiWZyJHXbGKiizjm3QwKGP

