app:
  config:
    keycloak:
      server-url: http://host.docker.internal:8080
      realm: banking-service
      client-id: banking-service-client
      client-secret: XbEay2NJMxYzieK8NSIkZHDpzD6EVQtN

spring:
  application:
    name: account-service
    ok: 200
    success: 200
    not_found: 404
    bad_request: 400
    conflict: 409

  security:
    enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
