
services:

  api-gateway:
    build: ./API-Gateway
    container_name: api-gateway
    ports:
      - "8085:8080"
    environment:
      KEYCLOAK_URL: http://host.docker.internal:8080
    depends_on:
      - user-service
      - account-service
      - fund-transfer-service
      - transaction-service
      - sequence-generator

  user-service:
    build: ./User-Service
    container_name: user-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_APPLICATION_SUCCESS: 200
      SPRING_APPLICATION_NOT_FOUND: 404
      SPRING_APPLICATION_BAD_REQUEST: 400
      SPRING_APPLICATION_CONFLICT: 409
    depends_on:
      mysql:
        condition: service_healthy

  account-service:
    build: ./Account-Service
    container_name: account-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/account_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_APPLICATION_BAD_REQUEST: 400
      SPRING_APPLICATION_CONFLICT: 409
      SPRING_APPLICATION_NOT_FOUND: 404
    depends_on:
      mysql:
        condition: service_healthy

  fund-transfer-service:
    build: ./Fund-Transfer
    container_name: fund-transfer-service
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fund_transfer_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_APPLICATION_BAD_REQUEST: 400
    depends_on:
      mysql:
        condition: service_healthy

  transaction-service:
    build: ./Transaction-Service
    container_name: transaction-service
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/transaction_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      mysql:
        condition: service_healthy

  sequence-generator:
    build: ./Sequence-Generator
    container_name: sequence-generator
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sequence_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
     - ./mysql-init:/docker-entrypoint-initdb.d
    # - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  mysql_data:
